GUARD-3057 Remove Netco ActionPolicy and Logger
skuvault-integrations/3dCartAccess pull request #14
Opened 2023-08-07 21:12 UTC by maxim-skuvault

[GUARD-3057]

Summary: Remove Netco ActionPolicy and logger implementation.

## Background
Need to stop using Netco in order to be .NET Standard-compatible

## About these changes
Based on https://github.com/skuvault-integrations/3dCartAccess/pull/13 code and ideas.
- Replace Netco logger with `Microsoft.Extensions.Logging.ILogger` using dependency injection.
- Replace Netco ActionPolicy with Polly retry policies.
- [Refactoring] Inject ThreeDCartSettings (RestApiKey) into ThreeDCartFactory constructor. Remove RestApiPrivateKey from RestThreeDCartConfig since it's not tenant-specific.
- [Refactoring] Extract the duplicate test credentials .csv reader methods into base classes: one for SOAP and another for REST.

# PR Readiness Checklist

- [ ] I have updated all relevant configuration
- [ ] Followed [development conventions][1] to the best of my ability
- [ ] Code is documented, particularly public interfaces and hard-to-understand areas
- [ ] Tests are updated / added and all pass
- [ ] Performed a self-review of my own code
- [ ] Acceptance criterias are confirmed by testing changes in UI (or another appropriate way)
- [ ] Confluence documentation is updated, if needed
- [ ] New code does not generate new warnings

[1]: https://agileharbor.atlassian.net/wiki/spaces/DEV/pages/1114130/Conventions

2023-08-09 19:47 UTC, reydelleon-skuvault requested changes

2023-08-15 17:39 UTC, maxim-skuvault commented on src/ThreeDCartAccess/DependencyInjection/ServiceCollectionExtensions.cs
> +	/// <exception cref="ArgumentNullException">If the <see cref="IServiceCollection"/> provided is null</exception>
@reydelleon-skuvault [Done](https://github.com/skuvault-integrations/3dCartAccess/pull/14/files#diff-8289d1edbb4470553a4d8ac858164afe6ebe4c0f2533878fc1e787336482a50bR23)

2023-08-15 17:42 UTC, maxim-skuvault commented on src/ThreeDCartAccess/RestApi/Misc/WebRequestServices.cs
> +			return new Exception( string.Format( "Marker: '{Mark}'. GET call for url '{1}' failed", marker, url ), ex );
@reydelleon-skuvault [Done](https://github.com/skuvault-integrations/3dCartAccess/pull/14/files#diff-850d97ebcfdc23e2b5140b6dcc5c3af45824226814d9a5a32e773c516bb8e5ccR251). Here we're building a string for the exception, not creating the string with field placeholders for the log. The methods that call this don't explicitly log in *access. They just throw and let v1 log.

2023-08-15 17:44 UTC, maxim-skuvault commented on src/ThreeDCartAccess/RestApi/ThreeDCartOrdersService.cs
> +				var portion = Resilience.Policies.Get( this._logger ).Execute( () => this.WebRequestServices.GetResponse< List< ThreeDCartOrder > >( endpoint, marker ) );
@reydelleon-skuvault Renamed to [ResiliencePolicies](https://github.com/skuvault-integrations/3dCartAccess/pull/14/files#diff-106a56444ccffbf7a7af73cb8b9fa0d042b61ae0588543ba523a027f029e91c1R9). I think `PolicyRegistry` is a specific Polly class we're not using here.

2023-08-18 14:27 UTC, reydelleon-skuvault approved these changes

2023-09-05 06:02 UTC, SShumer approved these changes

2023-09-05 13:13 UTC, merged